import {useEffect,useState} from 'react';
import {api,API} from '@/lib/api';
import {formatINR} from '@/lib/config';
import {useAuth} from '@/context/AuthContext';
import {ArrowLeft,Bell,Check,Copy,RefreshCw,XCircle} from 'lucide-react';
import {Link} from 'react-router-dom';

export default function AdminPayments(){
 const{token}=useAuth();const[payments,setPayments]=useState<any[]>([]);const[error,setError]=useState('');const[live,setLive]=useState(false);const[copied,setCopied]=useState('');const[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);try{setError('');const d=await api<any>('/api/admin/payments');setPayments(d.payments||[])}catch(e){setError(e instanceof Error?e.message:'Failed to load payments')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!token)return;const es=new EventSource(`${API}/api/admin/events?token=${encodeURIComponent(token)}`);es.addEventListener('connected',()=>setLive(true));es.addEventListener('payment_submitted',load);es.addEventListener('payment_updated',load);es.addEventListener('new_order',load);es.onerror=()=>setLive(false);return()=>es.close()},[token]);
 const verify=async(p:any,status:'verified'|'rejected'|'pending')=>{try{await api(`/api/admin/payments/${p.id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:'Payment update failed')}};
 const copy=(v:string)=>{navigator.clipboard?.writeText(v);setCopied(v);setTimeout(()=>setCopied(''),1200)};
 const pending=payments.filter(p=>p.status==='pending').length;const verified=payments.filter(p=>p.status==='verified').reduce((s,p)=>s+Number(p.amount||0),0);
 return <div className="min-h-screen bg-[#07090f] text-white px-4 sm:px-6 py-8 pt-24"><div className="max-w-7xl mx-auto">
  <div className="flex flex-col sm:flex-row justify-between gap-4 mb-7"><div><div className="flex items-center gap-3"><Link to="/admin" className="text-slate-400 hover:text-white"><ArrowLeft/></Link><h1 className="text-3xl font-black">Payment Verification</h1><span className={`text-xs font-bold px-2.5 py-1 rounded-full ${live?'bg-emerald-500/15 text-emerald-300':'bg-amber-500/15 text-amber-300'}`}>● {live?'LIVE':'RECONNECTING'}</span></div><p className="text-slate-400 mt-2">Every UTR appears here after submission. Verify the transaction before treating it as genuine.</p></div><button onClick={load} className="self-start px-4 py-2 rounded-xl border border-white/10 flex gap-2 items-center"> <RefreshCw size={17}/> Refresh</button></div>
  {error&&<div className="mb-5 rounded-2xl bg-red-500/10 border border-red-500/20 text-red-300 p-4">{error}</div>}
  <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6"><div className="bg-white text-slate-900 rounded-2xl p-5"><span className="text-sm text-slate-500">Total submissions</span><b className="block text-2xl mt-1">{payments.length}</b></div><div className="bg-white text-slate-900 rounded-2xl p-5"><span className="text-sm text-slate-500">Pending verification</span><b className="block text-2xl mt-1">{pending}</b></div><div className="bg-white text-slate-900 rounded-2xl p-5"><span className="text-sm text-slate-500">Verified amount</span><b className="block text-2xl mt-1">{formatINR(verified)}</b></div></div>
  <div className="bg-white text-slate-900 rounded-3xl overflow-hidden"><div className="p-5 border-b"><h2 className="font-black text-lg">All Payments</h2><p className="text-xs text-slate-500">Source shows whether it was a product purchase, Buy Me a Coffee, or a relief campaign.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-4 text-left">Date</th><th className="p-4 text-left">Username</th><th className="p-4 text-left">Amount</th><th className="p-4 text-left">Paid For</th><th className="p-4 text-left">UTR / Transaction ID</th><th className="p-4 text-left">Status</th><th className="p-4 text-left">Action</th></tr></thead><tbody>{payments.map(p=><tr key={`${p.kind}-${p.id}`} className="border-t align-top"><td className="p-4 whitespace-nowrap text-xs text-slate-500">{p.created_at?new Date(p.created_at).toLocaleString():''}</td><td className="p-4 min-w-48"><b>{p.username||'—'}</b><div className="text-xs text-slate-500">{p.email||''}</div></td><td className="p-4 font-black whitespace-nowrap">{formatINR(p.amount)}</td><td className="p-4 min-w-52"><b>{p.purpose}</b><div className="text-xs text-slate-500 mt-1 capitalize">{p.source?.replaceAll('_',' ')}</div>{p.campaign&&<div className="text-xs text-slate-400">{p.campaign}</div>}</td><td className="p-4 min-w-56">{p.utr?<div className="flex items-center gap-2"><code className="bg-slate-100 rounded-lg px-2 py-1 break-all">{p.utr}</code><button onClick={()=>copy(p.utr)} title="Copy UTR" className="p-1.5 rounded-lg hover:bg-slate-100"><Copy size={15}/></button>{copied===p.utr&&<span className="text-[10px] text-emerald-600">Copied</span>}</div>:<span className="text-red-500">No UTR</span>}</td><td className="p-4"><span className={`font-black capitalize ${p.status==='verified'?'text-emerald-600':p.status==='rejected'?'text-red-600':'text-amber-600'}`}>{p.status}</span></td><td className="p-4 min-w-44">{p.status==='pending'?<div className="flex gap-2"><button onClick={()=>verify(p,'verified')} className="rounded-xl bg-emerald-600 text-white px-3 py-2 font-bold flex items-center gap-1"><Check size={15}/> Verify</button><button onClick={()=>verify(p,'rejected')} className="rounded-xl border border-red-200 text-red-600 px-3 py-2"><XCircle size={16}/></button></div>:<button onClick={()=>verify(p,'pending')} className="text-xs text-violet-600 font-bold">Move to pending</button>}</td></tr>)}</tbody></table>{!loading&&!payments.length&&<div className="p-10 text-center text-slate-500">No UTR submissions yet.</div>}</div></div>
  <div className="mt-5 text-xs text-slate-500 flex items-center gap-2"><Bell size={14}/> Live updates are enabled. Admin verification is manual; submitting a UTR never auto-confirms a payment.</div>
 </div></div>
}
