import {useEffect,useMemo,useState} from 'react';
import {api,API} from '@/lib/api';
import {formatINR} from '@/lib/config';
import {useAuth} from '@/context/AuthContext';
import {Bell,Box,Check,Edit3,MapPin,Plus,RefreshCw,Save,Settings,Trash2,Users,X,Copy,CreditCard,Heart} from 'lucide-react';

const blank={name:'',slug:'',description:'',short_description:'',price:'',original_price:'',image_url:'',images:'',category_id:'',tags:'',variants:'',sizes:'',stock:0,is_active:true,is_new:false,is_featured:false};
const input='w-full rounded-xl border border-slate-300 bg-white text-slate-900 px-3 py-2.5 outline-none focus:border-violet-500';
const darkInput='w-full rounded-xl border border-slate-700 bg-[#0b0f18] text-white px-3 py-2.5 outline-none focus:border-violet-400';
function Modal({children,close}:{children:any;close:()=>void}){return <div className="fixed inset-0 z-[100] bg-black/70 p-4 overflow-y-auto"><div className="max-w-3xl mx-auto mt-8 rounded-3xl bg-[#0d111b] border border-white/10 p-6 text-white"><button onClick={close} className="float-right text-slate-400"><X/></button>{children}</div></div>}
function Toast({text,close}:{text:string;close:()=>void}){return <div className="fixed right-4 top-24 z-[110] rounded-2xl border border-emerald-400/30 bg-[#111827] text-white shadow-2xl px-4 py-3 flex items-center gap-3"><Bell size={18} className="text-emerald-300"/><b className="text-sm">{text}</b><button onClick={close}><X size={15}/></button></div>}

export default function AdminControlCenter(){
 const{logout,token}=useAuth();
 const[tab,setTab]=useState<'orders'|'payments'|'products'|'users'|'settings'>('orders');
 const[orders,setOrders]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]);
 const[settings,setSettings]=useState({upi:'',delivery:'49',gst:'0',freeThreshold:'999'});
 const[product,setProduct]=useState<any>(null),[address,setAddress]=useState<any>(null),[toast,setToast]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[live,setLive]=useState(false),[copied,setCopied]=useState('');
 const parseSettings=(raw:any)=>{const v=raw?.settings?.upi_id||'';try{const x=JSON.parse(v);if(x&&typeof x==='object')return{upi:String(x.upi||''),delivery:String(x.delivery??49),gst:String(x.gst??0),freeThreshold:String(x.freeThreshold??999)}}catch{}return{upi:String(raw?.settings?.upi||v),delivery:String(raw?.settings?.delivery??49),gst:String(raw?.settings?.gst??0),freeThreshold:String(raw?.settings?.freeThreshold??999)}};
 const load=async()=>{try{setError('');const[o,p,u,s,pm]=await Promise.all([api<any>('/api/admin/orders'),api<any>('/api/admin/products'),api<any>('/api/admin/users'),api<any>('/api/admin/settings'),api<any>('/api/admin/payments')]);setOrders(o.data||[]);setProducts(p.products||[]);setUsers(u.users||[]);setSettings(parseSettings(s));setPayments(pm.payments||[])}catch(e){setError(e instanceof Error?e.message:'Failed to load admin data')}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!token)return;const es=new EventSource(`${API}/api/admin/events?token=${encodeURIComponent(token)}`);es.addEventListener('connected',()=>setLive(true));es.addEventListener('new_order',(e)=>{const d=JSON.parse((e as MessageEvent).data);setToast(`🔔 New order: ${d.order?.order_id||'New order'}`);load()});es.addEventListener('payment_submitted',(e)=>{const d=JSON.parse((e as MessageEvent).data);setToast(`💳 New UTR submitted: ${d.donation?.donation_id||d.order?.order_id||'Payment'}`);load()});['order_updated','payment_updated','donation_created','product_updated','user_updated','settings_updated'].forEach(x=>es.addEventListener(x,()=>load()));es.onerror=()=>setLive(false);return()=>es.close()},[token]);
 const stats=useMemo(()=>({orders:orders.length,revenue:payments.filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.amount||0),0),pending:payments.filter(x=>x.status==='pending').length,products:products.length}),[orders,payments,products]);
 const orderUpdate=async(id:string,payload:any,msg='Order updated')=>{try{await api(`/api/admin/orders/${id}`,{method:'PATCH',body:JSON.stringify(payload)});setToast(msg);load()}catch(e){setError(e instanceof Error?e.message:'Order update failed')}};
 const donationUpdate=async(id:string,status:string)=>{try{await api(`/api/admin/donations/${id}`,{method:'PATCH',body:JSON.stringify({paymentStatus:status})});setToast(status==='paid'?'Donation payment verified ✓':'Donation payment updated');load()}catch(e){setError(e instanceof Error?e.message:'Payment update failed')}};
 const saveAddress=async()=>{if(!address)return;setSaving(true);try{await orderUpdate(address.id,{shippingAddress:address.value},'Address saved');setAddress(null)}finally{setSaving(false)}};
 const editProduct=(p:any)=>setProduct({id:p.id,name:p.name||'',slug:p.slug||'',description:p.description||'',short_description:p.short_description||'',price:p.price??'',original_price:p.original_price??'',image_url:p.image_url||'',images:(p.images||[]).join('\n'),category_id:p.category_id||'',tags:(p.tags||[]).join(', '),variants:(p.variants||[]).join(', '),sizes:(p.sizes||[]).join(', '),stock:p.stock??0,is_active:p.is_active!==false,is_new:!!p.is_new,is_featured:!!p.is_featured});
 const saveProduct=async()=>{if(!product)return;setSaving(true);try{const p={...product};delete p.id;delete p.created_at;delete p.updated_at;p.price=Number(p.price);p.original_price=p.original_price===''?null:Number(p.original_price);p.stock=Number(p.stock)||0;p.images=String(p.images||'').split(/\n|,/).map((x:string)=>x.trim()).filter(Boolean);p.tags=String(p.tags||'').split(',').map((x:string)=>x.trim()).filter(Boolean);p.variants=String(p.variants||'').split(',').map((x:string)=>x.trim()).filter(Boolean);p.sizes=String(p.sizes||'').split(',').map((x:string)=>x.trim()).filter(Boolean);p.category=String(p.category_id||'').trim();delete p.category_id;if(product.id)await api(`/api/admin/products/${product.id}`,{method:'PATCH',body:JSON.stringify(p)});else await api('/api/admin/products',{method:'POST',body:JSON.stringify(p)});setProduct(null);setToast(product.id?'Product updated':'Product added');load()}catch(e){setError(e instanceof Error?e.message:'Product save failed')}finally{setSaving(false)}};
 const removeProduct=async(id:string)=>{if(!confirm('Delete this product?'))return;try{await api(`/api/admin/products/${id}`,{method:'DELETE'});setToast('Product deleted');load()}catch(e){setError(e instanceof Error?e.message:'Delete failed')}};
 const saveUser=async(u:any)=>{try{await api(`/api/admin/users/${u.id}`,{method:'PATCH',body:JSON.stringify({name:u.name,email:u.email,role:u.role})});setToast('User updated');load()}catch(e){setError(e instanceof Error?e.message:'User update failed')}};
 const saveSettings=async()=>{setSaving(true);try{await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify({upi:settings.upi,delivery:Number(settings.delivery)||0,gst:Number(settings.gst)||0,freeThreshold:Number(settings.freeThreshold)||999})});setToast('UPI, delivery & GST saved');load()}catch(e){setError(e instanceof Error?e.message:'Settings save failed')}finally{setSaving(false)}};
 const copyUtr=(v:string)=>{navigator.clipboard?.writeText(v);setCopied(v);setTimeout(()=>setCopied(''),1200)};
 return <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 pt-24 text-slate-100">
  <div className="flex flex-col sm:flex-row justify-between gap-4 mb-7"><div><div className="flex items-center gap-3"><h1 className="text-3xl font-black text-white">Admin Control Center</h1><span className={`text-xs font-bold px-2.5 py-1 rounded-full ${live?'bg-emerald-500/15 text-emerald-300':'bg-amber-500/15 text-amber-300'}`}>● {live?'LIVE':'RECONNECTING'}</span></div><p className="text-slate-400 mt-1">Orders, payments, customers, addresses, products and store settings</p></div><div className="flex gap-2"><button onClick={load} className="px-3 py-2 rounded-xl border border-white/10"><RefreshCw size={17}/></button><button onClick={()=>{logout();location.href='/admin-login'}} className="px-4 py-2 rounded-xl border border-white/10">Logout</button></div></div>
  {error&&<div className="mb-5 rounded-xl bg-red-500/10 border border-red-500/20 text-red-300 p-3">{error}</div>}
  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">{[['Orders',stats.orders],['Verified Payments',formatINR(stats.revenue)],['Pending Verification',stats.pending],['Products',stats.products]].map(([l,v])=><div key={String(l)} className="bg-white rounded-2xl p-5 text-slate-900"><span className="text-sm text-slate-500">{l}</span><b className="block text-2xl mt-1">{v}</b></div>)}</div>
  <div className="flex gap-2 overflow-x-auto mb-5">{([['orders','Orders',Bell],['payments','Payments',CreditCard],['products','Products',Box],['users','Users & Addresses',Users],['settings','Store Settings',Settings]] as const).map(([k,l,I])=><button key={k} onClick={()=>setTab(k)} className={`shrink-0 px-4 py-2.5 rounded-xl text-sm font-bold flex items-center gap-2 ${tab===k?'bg-white text-slate-950':'bg-white/5 text-slate-400 border border-white/10'}`}><I size={16}/>{l}</button>)}</div>
  {tab==='payments'&&<div className="bg-white rounded-3xl overflow-hidden text-slate-900"><div className="p-5 border-b"><h2 className="font-black text-lg">Payment Verification</h2><p className="text-xs text-slate-500">Every UTR appears here immediately after the customer submits it. Verify the transaction yourself before marking it paid.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-700"><tr><th className="p-4 text-left">Customer</th><th className="p-4 text-left">Amount</th><th className="p-4 text-left">Payment For</th><th className="p-4 text-left">UTR / Transaction ID</th><th className="p-4 text-left">Status</th><th className="p-4 text-left">Time</th></tr></thead><tbody>{payments.map(p=><tr key={`${p.type}-${p.id}`} className="border-t align-top"><td className="p-4"><b>{p.username||'Unknown'}</b><div className="text-xs text-slate-500">{p.reference_id}</div></td><td className="p-4 font-black whitespace-nowrap">{formatINR(p.amount)}</td><td className="p-4 min-w-52"><div className="font-bold flex items-center gap-2">{p.type==='donation'?<Heart size={15} className="text-rose-500"/>:<Box size={15} className="text-violet-500"/>}{p.source}</div>{p.campaign&&<div className="text-xs text-slate-500 mt-1">{p.campaign}</div>}</td><td className="p-4 min-w-56">{p.utr?<div className="flex items-center gap-2"><code className="text-xs bg-slate-100 rounded px-2 py-1 break-all">{p.utr}</code><button onClick={()=>copyUtr(p.utr)}><Copy size={14}/></button>{copied===p.utr&&<span className="text-[10px] text-emerald-600">Copied</span>}</div>:<span className="text-red-500">UTR missing</span>}</td><td className="p-4 min-w-36"><div className={`font-bold capitalize ${p.status==='paid'?'text-emerald-600':p.status==='rejected'||p.status==='failed'?'text-red-600':'text-amber-600'}`}>{p.status}</div>{p.type==='donation'?<select value={p.status} onChange={e=>donationUpdate(p.id,e.target.value)} className="border rounded-lg p-1.5 bg-white mt-2"><option>pending</option><option>paid</option><option>rejected</option><option>failed</option></select>:<select value={p.status} onChange={e=>orderUpdate(p.id,{paymentStatus:e.target.value},e.target.value==='paid'?'Product payment verified ✓':'Payment status updated')} className="border rounded-lg p-1.5 bg-white mt-2"><option>pending</option><option>paid</option><option>failed</option><option>refunded</option></select>}</td><td className="p-4 text-xs text-slate-500 whitespace-nowrap">{p.created_at?new Date(p.created_at).toLocaleString():''}</td></tr>)}</tbody></table>{!payments.length&&<div className="p-10 text-center text-slate-500">No payments yet.</div>}</div></div>}
  {tab==='orders'&&<div className="bg-white rounded-3xl overflow-hidden text-slate-900"><div className="p-5 border-b"><h2 className="font-black text-lg">All Orders</h2><p className="text-xs text-slate-500">Live updates enabled — no manual refresh required. Verify UTR before marking paid.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-700"><tr><th className="p-4 text-left">Order</th><th className="p-4 text-left">Customer</th><th className="p-4 text-left">Delivery Address</th><th className="p-4 text-left">Amount</th><th className="p-4 text-left">Payment / UTR</th><th className="p-4 text-left">Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-t align-top"><td className="p-4 font-bold whitespace-nowrap">{o.order_id}<div className="text-xs text-slate-400 mt-1">{o.created_at?new Date(o.created_at).toLocaleString():''}</div></td><td className="p-4 min-w-48"><b>{o.customer_name}</b><div className="text-xs text-slate-500">{o.email}</div><div className="text-xs text-slate-500">{o.phone}</div></td><td className="p-4 min-w-72 text-slate-600"><MapPin className="inline w-4 h-4"/> {o.address}{o.apartment?`, ${o.apartment}`:''}<br/>{o.city}, {o.state} — {o.pincode}<br/><button onClick={()=>setAddress({id:o.id,value:{name:o.customer_name,phone:o.phone,address:o.address,apartment:o.apartment||'',city:o.city,state:o.state,pincode:o.pincode}})} className="text-violet-600 font-bold text-xs mt-2"><Edit3 className="inline w-3.5 h-3.5"/> Edit address</button></td><td className="p-4 font-bold whitespace-nowrap"><div>{formatINR(o.total_amount)}</div><div className="text-xs text-slate-500 mt-1">Subtotal {formatINR(o.subtotal)} · Delivery {formatINR(o.delivery_charge||0)} · GST {formatINR(o.gst_amount||0)}</div></td><td className="p-4 min-w-56"><div className={`font-bold capitalize ${o.payment_status==='paid'?'text-emerald-600':'text-amber-600'}`}>{o.payment_status}</div>{o.payment_reference?<div className="mt-2 flex items-center gap-2"><code className="text-xs bg-slate-100 rounded px-2 py-1 break-all">{o.payment_reference}</code><button onClick={()=>copyUtr(o.payment_reference)}><Copy size={14}/></button></div>:<div className="text-xs text-red-500 mt-2">UTR not submitted</div>}<select value={o.payment_status} onChange={e=>orderUpdate(o.id,{paymentStatus:e.target.value},e.target.value==='paid'?'Payment verified — marked paid':'Payment status updated')} className="border rounded-lg p-1.5 bg-white mt-2"><option>pending</option><option>paid</option><option>failed</option><option>refunded</option></select></td><td className="p-4"><select value={o.order_status} onChange={e=>orderUpdate(o.id,{status:e.target.value})} className="border rounded-lg p-1.5 bg-white"><option>pending</option><option>confirmed</option><option>processing</option><option>shipped</option><option>delivered</option><option>cancelled</option></select></td></tr>)}</tbody></table></div></div>}
  {tab==='products'&&<div><div className="flex justify-between items-center mb-4"><div><h2 className="text-xl font-black">Product Management</h2><p className="text-slate-500 text-sm">Manage price, details, images, tags, variants, sizes, stock and visibility.</p></div><button onClick={()=>setProduct({...blank})} className="px-4 py-2.5 rounded-xl bg-white text-slate-950 font-black"><Plus className="inline" size={17}/> Add</button></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{products.map(p=><div key={p.id} className="bg-white text-slate-900 rounded-2xl overflow-hidden"><div className="aspect-video bg-slate-100">{p.image_url&&<img src={p.image_url} alt="" className="w-full h-full object-cover"/>}</div><div className="p-4"><h3 className="font-black">{p.name}</h3><p className="text-xs text-slate-500">{formatINR(p.price)} · Stock {p.stock}</p><div className="flex flex-wrap gap-1 mt-2">{(p.tags||[]).map((t:string)=><span key={t} className="text-[10px] bg-violet-50 text-violet-700 px-2 py-1 rounded-full">#{t}</span>)}</div><div className="flex gap-2 mt-4"><button onClick={()=>editProduct(p)} className="flex-1 rounded-xl bg-slate-900 text-white py-2 font-bold"><Edit3 className="inline mr-1" size={15}/>Edit</button><button onClick={()=>removeProduct(p.id)} className="rounded-xl border border-red-200 text-red-600 px-3"><Trash2 size={16}/></button></div></div></div>)}</div></div>}
  {tab==='users'&&<div className="bg-white text-slate-900 rounded-3xl overflow-hidden"><div className="p-5 border-b"><h2 className="font-black text-lg">Users & Addresses</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-4 text-left">Name</th><th className="p-4 text-left">Email / ID</th><th className="p-4 text-left">Role</th><th className="p-4 text-left">Latest Address</th><th className="p-4">Save</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t align-top"><td className="p-4"><input className={input} value={u.name||''} onChange={e=>setUsers(xs=>xs.map(x=>x.id===u.id?{...x,name:e.target.value}:x))}/></td><td className="p-4"><input className={input} value={u.email||''} onChange={e=>setUsers(xs=>xs.map(x=>x.id===u.id?{...x,email:e.target.value}:x))}/></td><td className="p-4"><select className={input} value={u.role} onChange={e=>setUsers(xs=>xs.map(x=>x.id===u.id?{...x,role:e.target.value}:x))}><option value="customer">Customer</option><option value="admin">Admin</option></select></td><td className="p-4 min-w-72 text-xs text-slate-600">{u.latest_order?<>{u.latest_order.address}{u.latest_order.apartment?`, ${u.latest_order.apartment}`:''}<br/>{u.latest_order.city}, {u.latest_order.state} — {u.latest_order.pincode}<br/>📞 {u.latest_order.phone}</>:'No order/address yet'}</td><td className="p-4"><button onClick={()=>saveUser(u)} className="px-3 py-2 rounded-lg bg-slate-900 text-white"><Check size={15}/></button></td></tr>)}</tbody></table></div></div>}
  {tab==='settings'&&<div className="max-w-2xl bg-white text-slate-900 rounded-3xl p-6"><h2 className="text-xl font-black">Store Settings</h2><p className="text-sm text-slate-500 mt-1">Admin-controlled values used in checkout and direct UPI payment.</p><div className="grid sm:grid-cols-2 gap-4 mt-6"><label className="sm:col-span-2 font-bold">UPI ID<input className={input+' mt-2'} value={settings.upi} onChange={e=>setSettings({...settings,upi:e.target.value})} placeholder="yourupi@bank"/></label><label className="font-bold">Delivery Charges (₹)<input type="number" min="0" className={input+' mt-2'} value={settings.delivery} onChange={e=>setSettings({...settings,delivery:e.target.value})}/></label><label className="font-bold">GST (%)<input type="number" min="0" step="0.01" className={input+' mt-2'} value={settings.gst} onChange={e=>setSettings({...settings,gst:e.target.value})}/></label><label className="font-bold">Free Delivery Above (₹)<input type="number" min="0" className={input+' mt-2'} value={settings.freeThreshold} onChange={e=>setSettings({...settings,freeThreshold:e.target.value})}/></label></div><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600"><b>Checkout:</b> Subtotal + Delivery + GST = Final Total. Customer pays directly to this UPI ID.</div><button disabled={saving} onClick={saveSettings} className="mt-5 px-5 py-2.5 rounded-xl bg-violet-600 text-white font-bold"><Save className="inline mr-2" size={16}/>{saving?'Saving…':'Save Settings'}</button></div>}
  {product&&<Modal close={()=>setProduct(null)}><h2 className="text-xl font-black mb-5">{product.id?'Edit Product':'Add Product'}</h2><div className="grid md:grid-cols-2 gap-4">{[['name','Name'],['slug','Slug'],['category_id','Category'],['price','Price'],['original_price','Original Price'],['stock','Stock'],['image_url','Primary Image URL'],['tags','Tags (comma separated)'],['variants','Variants (comma separated)'],['sizes','Sizes (comma separated)']].map(([k,l])=><label key={k}>{l}<input className={darkInput} value={product[k]??''} onChange={e=>setProduct({...product,[k]:e.target.value})}/></label>)}<label className="md:col-span-2">More image URLs<textarea rows={3} className={darkInput} value={product.images||''} onChange={e=>setProduct({...product,images:e.target.value})}/></label><label className="md:col-span-2">Short description<textarea rows={2} className={darkInput} value={product.short_description||''} onChange={e=>setProduct({...product,short_description:e.target.value})}/></label><label className="md:col-span-2">Description<textarea rows={4} className={darkInput} value={product.description||''} onChange={e=>setProduct({...product,description:e.target.value})}/></label></div><div className="flex gap-5 mt-5 text-sm"><label><input type="checkbox" checked={product.is_active!==false} onChange={e=>setProduct({...product,is_active:e.target.checked})}/> Active</label><label><input type="checkbox" checked={!!product.is_featured} onChange={e=>setProduct({...product,is_featured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={!!product.is_new} onChange={e=>setProduct({...product,is_new:e.target.checked})}/> New</label></div><button disabled={saving} onClick={saveProduct} className="mt-6 px-5 py-2.5 rounded-xl bg-violet-600 font-bold">Save product</button></Modal>}
  {address&&<Modal close={()=>setAddress(null)}><h2 className="text-xl font-black mb-5">Edit Customer Delivery Address</h2><div className="grid md:grid-cols-2 gap-4">{[['name','Name'],['phone','Phone'],['address','Address'],['apartment','Apartment / Floor'],['city','City'],['state','State'],['pincode','Pincode']].map(([k,l])=><label key={k} className={k==='address'?'md:col-span-2':''}>{l}<input className={darkInput} value={address.value[k]||''} onChange={e=>setAddress({...address,value:{...address.value,[k]:e.target.value}})}/></label>)}</div><button disabled={saving} onClick={saveAddress} className="mt-6 px-5 py-2.5 rounded-xl bg-violet-600 font-bold">Save address</button></Modal>}
  {toast&&<Toast text={toast} close={()=>setToast('')}/>}</div>
}
