import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {CheckCircle,Clock,Package,MapPin,CreditCard,ArrowRight,RefreshCw} from 'lucide-react';
import {api} from '@/lib/api';
import {formatINR} from '@/lib/config';

export default function MyOrders(){
 const [orders,setOrders]=useState<any[]>([]);const [busy,setBusy]=useState(true);const [err,setErr]=useState('');const nav=useNavigate();
 const load=async()=>{setBusy(true);setErr('');try{const d=await api<{data:any[]}>('/api/orders');setOrders(d.data||[])}catch(e){setErr(e instanceof Error?e.message:'Unable to load orders')}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const paymentLabel=(s:string)=>s==='paid'?'Paid':s==='rejected'?'Rejected':s==='failed'?'Failed':'Payment Pending';
 return <div className="min-h-screen bg-[#07090f] text-white"><main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-32 pb-20">
  <div className="flex items-end justify-between gap-4 mb-8"><div><p className="text-violet-300 text-xs font-black tracking-[.2em]">ACCOUNT</p><h1 className="text-4xl sm:text-5xl font-black mt-2">My Orders</h1><p className="text-slate-500 mt-2">Your previous orders, payment status and order details.</p></div><button onClick={load} className="p-3 rounded-xl border border-white/10 bg-white/5 text-slate-300 hover:text-white" title="Refresh"><RefreshCw size={18}/></button></div>
  {busy&&<div className="rounded-3xl border border-white/10 bg-[#0d111b] p-8 text-center text-slate-400">Loading your orders…</div>}
  {!busy&&err&&<div className="rounded-3xl border border-red-500/20 bg-red-500/5 p-6 text-center text-red-300">{err}</div>}
  {!busy&&!err&&!orders.length&&<div className="rounded-3xl border border-white/10 bg-[#0d111b] p-10 text-center"><Package className="mx-auto text-slate-600" size={36}/><h2 className="text-xl font-bold mt-4">No orders yet</h2><p className="text-slate-500 mt-2">Your placed orders will appear here.</p><Link to="/store" className="inline-flex mt-5 px-5 py-3 rounded-xl bg-white text-black font-bold">Explore Store</Link></div>}
  {!busy&&!err&&orders.length>0&&<div className="space-y-5">{orders.map(o=><article key={o.id||o.order_id} className="rounded-3xl border border-white/10 bg-[#0d111b] overflow-hidden">
   <div className="p-5 sm:p-6 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5 border-b border-white/10"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs text-slate-500">Order ID</span><b>{o.order_id}</b><span className={`px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wide ${o.payment_status==='paid'?'bg-emerald-500/10 text-emerald-300':o.payment_status==='rejected'||o.payment_status==='failed'?'bg-red-500/10 text-red-300':'bg-amber-500/10 text-amber-300'}`}>{paymentLabel(o.payment_status)}</span></div><p className="text-xs text-slate-500 mt-2">{o.created_at?new Date(o.created_at).toLocaleString():''}</p></div><div className="text-left lg:text-right"><span className="text-xs text-slate-500">Total</span><b className="block text-2xl mt-1">{formatINR(o.total_amount)}</b></div></div>
   <div className="p-5 sm:p-6 grid lg:grid-cols-[1fr_auto] gap-6"><div><div className="space-y-3">{o.items?.map((i:any)=><div key={i.id} className="flex items-center justify-between gap-4 text-sm"><span className="text-slate-300 truncate">{i.product_name} × {i.quantity}{i.size?` · ${i.size}`:''}</span><b>{formatINR((Number(i.price)||0)*(Number(i.quantity)||0))}</b></div>)}</div><div className="mt-5 pt-5 border-t border-white/10 flex flex-wrap gap-4 text-xs text-slate-500"><span className="inline-flex items-center gap-1.5"><MapPin size={14}/>{o.city}, {o.state} {o.pincode}</span><span className="inline-flex items-center gap-1.5"><Package size={14}/>{o.order_status||'pending'}</span></div></div>
    <div className="lg:min-w-[190px] flex lg:flex-col gap-2 lg:justify-center">{o.payment_status==='paid'?<div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4"><div className="flex items-center gap-2 text-emerald-300 font-bold"><CheckCircle size={17}/> Payment verified</div>{o.payment_reference&&<p className="text-[11px] text-slate-500 mt-2 break-all">UTR: <span className="text-slate-300">{o.payment_reference}</span></p>}</div>:<button onClick={()=>nav(`/order-confirmation/${encodeURIComponent(o.order_id)}`)} className="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-white text-black font-black hover:bg-violet-200 transition"><CreditCard size={17}/>{o.payment_status==='rejected'||o.payment_status==='failed'?'Pay Again':'Pay Now'}<ArrowRight size={15}/></button>}<Link to={`/track?id=${encodeURIComponent(o.order_id)}`} className="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-xl border border-white/10 bg-white/5 text-sm font-bold text-white hover:bg-white/10"><Clock size={16}/>Track Order</Link></div>
   </div>
  </article>)}</div>}
 </main></div>
}