import {useMemo,useState} from 'react';
import {ArrowLeft,Check,Coffee,Copy,ExternalLink,Heart,IndianRupee,Smartphone,ShieldCheck} from 'lucide-react';
import {Link} from 'react-router-dom';
import {api} from '@/lib/api';
import {formatINR,useSettings} from '@/lib/config';
import {useAuth} from '@/context/AuthContext';

const PRESETS=[50,100,200,500,1000];
const CAMPAIGNS=['Nepal Relief','Flood Relief','Earthquake Relief','Natural Disaster Emergency Relief'];

export default function Support(){
 const settings=useSettings(); const {user}=useAuth();
 const [mode,setMode]=useState<'coffee'|'relief'>('coffee'); const [selected,setSelected]=useState<number>(100); const [custom,setCustom]=useState(''); const [campaign,setCampaign]=useState(CAMPAIGNS[0]);
 const [utr,setUtr]=useState(''); const [submitted,setSubmitted]=useState(false); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState(''); const [copied,setCopied]=useState(false);
 const amount=selected===0?Number(custom):selected; const upi=String(settings.upi_id||'').trim(); const creator=String(settings.creator_name||'AccessStore').trim(); const valid=Number.isFinite(amount)&&amount>0;
 const upiLink=useMemo(()=>valid&&upi?`upi://pay?pa=${encodeURIComponent(upi)}&pn=${encodeURIComponent(creator)}&am=${amount.toFixed(2)}&cu=INR`:'' ,[amount,creator,upi,valid]);
 const qr=upiLink?`https://api.qrserver.com/v1/create-qr-code/?size=320x320&margin=12&data=${encodeURIComponent(upiLink)}`:'';
 const source=mode==='coffee'?'Buy me a coffee':campaign;
 const copy=async()=>{if(!upi)return;try{await navigator.clipboard.writeText(upi);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{}};
 const submit=async()=>{setError('');if(!user){setError('Please login first to submit your UTR.');return}if(!valid){setError('Enter a valid amount.');return}if(utr.trim().length<6){setError('Enter your UTR / transaction ID.');return}setSubmitting(true);try{await api('/api/donations',{method:'POST',body:JSON.stringify({amount,purpose:mode,campaign:mode==='relief'?campaign:'',utr})});setSubmitted(true)}catch(e){setError(e instanceof Error?e.message:'Could not submit payment')}finally{setSubmitting(false)}};
 return <div className="min-h-screen bg-[#07090f] text-white px-4 py-10 sm:py-16"><div className="max-w-4xl mx-auto">
  <Link to="/" className="inline-flex items-center gap-2 text-slate-400 hover:text-white text-sm font-semibold mb-8"><ArrowLeft size={17}/> Back to AccessStore</Link>
  <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-[#121722] via-[#0c1019] to-violet-500/10 p-5 sm:p-9">
   <div className="text-center"><div className="mx-auto w-16 h-16 rounded-2xl bg-violet-400/10 border border-violet-300/20 grid place-items-center text-violet-300">{mode==='coffee'?<Coffee size={30}/>:<Heart size={30}/>}</div><p className="mt-5 text-violet-300 text-xs font-black tracking-[.2em]">SUPPORT & RELIEF</p><h1 className="text-3xl sm:text-5xl font-black mt-2">Make a small difference ❤️</h1><p className="text-slate-400 mt-3 max-w-2xl mx-auto">Support AccessStore or contribute toward a disaster-relief cause. Payments are verified manually using the UTR you submit.</p></div>
   <div className="grid sm:grid-cols-2 gap-3 mt-8"><button onClick={()=>{setMode('coffee');setSubmitted(false);setError('')}} className={`rounded-2xl border p-4 text-left ${mode==='coffee'?'border-amber-300 bg-amber-400/10':'border-white/10 bg-white/5'}`}><Coffee className="text-amber-300"/><b className="block mt-2">Buy me a coffee ☕</b><span className="text-xs text-slate-400">Help keep AccessStore running.</span></button><button onClick={()=>{setMode('relief');setSubmitted(false);setError('')}} className={`rounded-2xl border p-4 text-left ${mode==='relief'?'border-rose-300 bg-rose-400/10':'border-white/10 bg-white/5'}`}><Heart className="text-rose-300"/><b className="block mt-2">Help & Disaster Relief</b><span className="text-xs text-slate-400">Contribute to a selected relief cause.</span></button></div>
   {mode==='relief'&&<div className="mt-6"><p className="text-sm font-bold text-slate-300 mb-3">Choose relief cause</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{CAMPAIGNS.map(c=><button key={c} onClick={()=>{setCampaign(c);setSubmitted(false)}} className={`rounded-xl border px-3 py-3 text-xs sm:text-sm font-bold ${campaign===c?'border-rose-300 bg-rose-400 text-black':'border-white/10 bg-white/5 text-white'}`}>{c}</button>)}</div></div>}
   <div className="mt-7"><p className="text-sm font-bold text-slate-300 mb-3">Choose an amount</p><div className="grid grid-cols-3 sm:grid-cols-6 gap-2">{PRESETS.map(v=><button key={v} onClick={()=>{setSelected(v);setCustom('');setSubmitted(false)}} className={`rounded-2xl border px-3 py-3 font-black ${selected===v?'border-violet-300 bg-violet-400 text-black':'border-white/10 bg-white/5 text-white hover:bg-white/10'}`}>{formatINR(v)}</button>)}<button onClick={()=>{setSelected(0);setSubmitted(false)}} className={`rounded-2xl border px-3 py-3 font-black ${selected===0?'border-violet-300 bg-violet-400 text-black':'border-white/10 bg-white/5 text-white hover:bg-white/10'}`}>Custom</button></div>{selected===0&&<div className="mt-3 relative"><IndianRupee size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500"/><input autoFocus inputMode="decimal" value={custom} onChange={e=>setCustom(e.target.value.replace(/[^0-9.]/g,''))} placeholder="Enter amount" className="w-full rounded-2xl border border-white/10 bg-black/30 py-4 pl-10 pr-4 outline-none focus:border-violet-300 text-white"/></div>}</div>
   <div className="mt-8 grid md:grid-cols-2 gap-6 items-center"><div className="rounded-3xl border border-white/10 bg-black/20 p-5 text-center">{qr&&valid?<img src={qr} alt="UPI payment QR code" className="mx-auto w-64 h-64 rounded-2xl bg-white p-2"/>:<div className="w-64 h-64 mx-auto rounded-2xl border border-dashed border-white/10 grid place-items-center text-slate-500">Enter a valid amount</div>}<p className="text-xs text-slate-500 mt-3">Pay {valid?formatINR(amount):'the selected amount'} to the UPI shown below.</p></div>
    <div><div className="rounded-3xl border border-white/10 bg-white/5 p-5"><p className="text-xs uppercase tracking-widest text-slate-500 font-bold">Purpose</p><p className="font-black mt-1">{source}</p><p className="text-xs text-slate-500 mt-3">Amount</p><p className="text-4xl font-black">{valid?formatINR(amount):'₹0'}</p><a href={upiLink||'#'} onClick={e=>{if(!upiLink)e.preventDefault()}} className={`mt-5 w-full inline-flex justify-center items-center gap-2 rounded-2xl px-5 py-3.5 font-black ${valid&&upi?'bg-violet-400 text-black hover:bg-violet-300':'bg-white/10 text-slate-500 pointer-events-none'}`}><Smartphone size={18}/> Pay with UPI app <ExternalLink size={16}/></a></div>
     <div className="mt-4 rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs text-slate-500 font-bold uppercase tracking-wider">UPI ID</p><div className="flex items-center gap-2 mt-2"><code className="flex-1 text-sm text-white break-all">{upi||'UPI ID not configured'}</code><button onClick={copy} disabled={!upi} className="p-2 rounded-xl bg-white/10 disabled:opacity-40">{copied?<Check size={17}/>:<Copy size={17}/>}</button></div></div></div></div>
   <div className="mt-7 rounded-3xl border border-emerald-400/20 bg-emerald-400/5 p-5"><div className="flex items-center gap-2 font-black"><ShieldCheck size={18} className="text-emerald-300"/> Submit payment proof</div><p className="text-xs text-slate-400 mt-2">After paying, enter the UTR / transaction ID. Admin will verify it before treating the payment as genuine.</p>{!user&&<p className="text-sm text-amber-300 mt-3">Please login to submit your UTR so your username is recorded.</p>}{submitted?<div className="mt-4 rounded-2xl bg-emerald-400/10 border border-emerald-300/20 p-4 text-emerald-200 font-bold">✓ UTR submitted. Payment is pending admin verification.</div>:<div className="mt-4 flex flex-col sm:flex-row gap-3"><input value={utr} onChange={e=>setUtr(e.target.value.slice(0,100))} placeholder="Enter UTR / Transaction ID" className="flex-1 rounded-2xl border border-white/10 bg-black/30 px-4 py-3.5 outline-none focus:border-emerald-300"/><button disabled={submitting||!user} onClick={submit} className="rounded-2xl bg-emerald-400 text-black px-6 py-3.5 font-black disabled:opacity-40">{submitting?'Submitting…':'Submit UTR'}</button></div>}{error&&<p className="text-sm text-red-300 mt-3">{error}</p>}</div>
   <div className="mt-5 text-center text-xs text-slate-500"><Heart size={13} className="inline text-rose-300 mr-1"/> For relief campaigns, the page identifies the cause clearly; verify the campaign details before contributing.</div>
  </div>
 </div></div>
}
