import {useEffect,useState} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {Search,ShoppingBag,Menu,X,ArrowUpRight,LogOut} from 'lucide-react';
import {useCart} from '@/context/CartContext';
import {useAuth} from '@/context/AuthContext';

export default function Navbar(){
 const [scrolled,setScrolled]=useState(false);const [open,setOpen]=useState(false);const [search,setSearch]=useState(false);const [q,setQ]=useState('');
 const {totalItems}=useCart();const {user,logout}=useAuth();const location=useLocation();const nav=useNavigate();
 useEffect(()=>{const fn=()=>setScrolled(window.scrollY>16);fn();window.addEventListener('scroll',fn);return()=>window.removeEventListener('scroll',fn)},[]);
 useEffect(()=>setOpen(false),[location.pathname]);
 const goSearch=(e:React.FormEvent)=>{e.preventDefault();if(q.trim()){nav(`/store?q=${encodeURIComponent(q.trim())}`);setQ('');setSearch(false)}};
 const handleLogout=()=>{logout();setOpen(false);nav('/');};
 const links=[['Shop','/store'],['Categories','/store'],['Track','/track'],['Support','/support']];
 return <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-300 ${scrolled?'bg-[#07090f]/95 backdrop-blur-xl border-b border-white/10':'bg-[#07090f]/95 backdrop-blur-xl border-b border-white/10'}`}>
  <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="h-[76px] flex items-center justify-between gap-5">
   <Link to="/" className="flex items-center gap-3 shrink-0"><span className="w-10 h-10 rounded-2xl bg-white text-black grid place-items-center font-black text-lg shadow-xl">A</span><span className="font-black tracking-tight text-lg text-white">ACCESS<span className="text-violet-400">STORE</span></span></Link>
   <div className="hidden md:flex items-center gap-1">{links.map(([label,path])=><Link key={label} to={path} className={`px-4 py-2 rounded-xl text-sm font-medium transition ${location.pathname===path?'text-white bg-white/10':'text-slate-400 hover:text-white hover:bg-white/5'}`}>{label}</Link>)}</div>
   <div className="flex items-center gap-1"><button onClick={()=>setSearch(v=>!v)} className="p-2.5 rounded-xl text-slate-300 hover:bg-white/10"><Search size={19}/></button><Link to="/cart" className="relative p-2.5 rounded-xl text-slate-300 hover:bg-white/10"><ShoppingBag size={19}/>{totalItems>0&&<span className="absolute -top-0.5 -right-0.5 min-w-5 h-5 px-1 rounded-full bg-violet-500 text-white text-[10px] font-bold grid place-items-center">{totalItems>99?'99+':totalItems}</span>}</Link>{user?<div className="hidden sm:flex items-center gap-2 ml-2"><Link to={user.role==='admin'?'/admin':'/orders'} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white text-black text-sm font-bold hover:bg-violet-200 transition">{user.role==='admin'?'Dashboard':'My Orders'}<ArrowUpRight size={15}/></Link><button onClick={handleLogout} title="Logout" className="flex items-center justify-center w-10 h-10 rounded-xl border border-white/10 bg-white/5 text-slate-300 hover:text-white hover:bg-red-500/15 hover:border-red-400/30 transition"><LogOut size={17}/></button></div>:<Link to="/login" className="hidden sm:block ml-2 px-4 py-2.5 rounded-xl border border-white/15 bg-white/5 text-sm font-bold hover:bg-white/10">Sign in</Link>}<button onClick={()=>setOpen(v=>!v)} className="md:hidden p-2.5 rounded-xl text-slate-300">{open?<X size={20}/>:<Menu size={20}/>}</button></div>
  </div>{search&&<div className="pb-4"><form onSubmit={goSearch} className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the store..." className="w-full h-12 rounded-2xl pl-11 pr-4 border border-white/10 bg-[#0d111b] outline-none focus:border-violet-400/60"/></form></div>}</nav>
  {open&&<div className="md:hidden mx-3 mb-3 rounded-2xl glass p-2">{links.map(([label,path])=><Link key={label} to={path} className="block px-4 py-3 rounded-xl text-sm text-slate-300 hover:bg-white/5">{label}</Link>)}{user?<><Link to={user.role==='admin'?'/admin':'/orders'} className="block px-4 py-3 rounded-xl text-sm font-semibold text-white">{user.role==='admin'?'Dashboard':'My Orders'}</Link><button onClick={handleLogout} className="w-full flex items-center gap-2 px-4 py-3 rounded-xl text-sm font-semibold text-red-300 hover:bg-red-500/10"><LogOut size={17}/>Logout</button></>:<Link to="/login" className="block px-4 py-3 rounded-xl text-sm font-semibold text-white">Sign in</Link>}</div>}
 </header>
}