import 'dotenv/config';
import express from 'express';import cors from 'cors';import mongoose from 'mongoose';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';import rateLimit from 'express-rate-limit';
import User from './models/User.js';import Product from './models/Product.js';import Order from './models/Order.js';import Settings from './models/Settings.js';import {addRealtimeClient,broadcast} from './realtime.js';
const app=express();
const allowedOrigins=['https://accessstore.vercel.app','http://localhost:5173','http://localhost:3000',process.env.CLIENT_URL,process.env.FRONTEND_URL].filter(Boolean).flatMap(v=>v.split(',').map(x=>x.trim())).filter(Boolean);
const corsOptions={origin:(origin,cb)=>{if(!origin||allowedOrigins.includes(origin))return cb(null,true);return cb(new Error('CORS origin not allowed'))},credentials:true,methods:['GET','POST','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization']};
app.use(cors(corsOptions));app.options('*',cors(corsOptions));app.use(express.json({limit:'1mb'}));
const authLimiter=rateLimit({windowMs:15*60*1000,limit:30,standardHeaders:true,legacyHeaders:false});
const publicUser=u=>({id:String(u._id),name:u.name||'',email:u.email,role:u.role});
const tokenFor=u=>jwt.sign({sub:String(u._id),role:u.role,email:u.email},process.env.JWT_SECRET,{expiresIn:'7d'});
async function auth(req,res,next){const raw=req.headers.authorization||'';if(!raw.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});try{const p=jwt.verify(raw.slice(7),process.env.JWT_SECRET);const u=await User.findById(p.sub);if(!u)return res.status(401).json({error:'Invalid or expired session'});req.user=u;next()}catch{return res.status(401).json({error:'Invalid or expired session'})}}
const adminOnly=(req,res,next)=>req.user?.role==='admin'?next():res.status(403).json({error:'Admin access required'});
function readStoreConfig(raw){let cfg={upi:'',delivery:49,gst:0,freeThreshold:999};try{const x=typeof raw==='string'?JSON.parse(raw):raw;if(x&&typeof x==='object'){cfg.upi=String(x.upi||'');cfg.delivery=Math.max(0,Number(x.delivery)||0);cfg.gst=Math.max(0,Number(x.gst)||0);cfg.freeThreshold=Math.max(0,Number(x.freeThreshold)||999)}}catch{cfg.upi=String(raw||'')}return cfg}
function productOut(p){return{id:String(p._id),name:p.name,slug:p.slug,description:p.description||'',short_description:p.short_description||'',price:p.price,original_price:p.original_price??null,discount_percentage:p.original_price?Math.max(0,Math.round((1-p.price/p.original_price)*100)):0,category_id:p.category||'',image_url:p.image_url||'',images:p.images||(p.image_url?[p.image_url]:[]),tags:p.tags||[],rating:p.rating||0,review_count:p.review_count||0,stock:p.stock||0,is_active:p.is_active!==false,is_featured:!!p.is_featured,is_new:!!p.is_new,variants:p.variants||[],sizes:p.sizes||[],created_at:p.createdAt?.toISOString?.()||p.createdAt,updated_at:p.updatedAt?.toISOString?.()||p.updatedAt}}
function orderOut(o){return{id:String(o._id),order_id:o.orderId,customer_name:o.shippingAddress?.name||'',email:o.email||'',phone:o.shippingAddress?.phone||'',address:o.shippingAddress?.address||'',apartment:o.shippingAddress?.apartment||null,city:o.shippingAddress?.city||'',state:o.shippingAddress?.state||'',pincode:o.shippingAddress?.pincode||'',total_amount:o.total,subtotal:o.subtotal,delivery_charge:o.shipping,shipping:o.shipping,gst_amount:o.gst,gst:o.gst,discount:0,coupon_code:null,payment_status:o.paymentStatus,order_status:o.status,payment_method:o.paymentProvider||'upi',payment_reference:o.paymentReference||null,estimated_delivery:o.estimatedDelivery||null,items:(o.items||[]).map((i,n)=>({id:`${o._id}-${n}`,order_id:o.orderId,product_id:String(i.product||''),product_name:i.name,product_image:i.image_url||'',quantity:i.quantity,price:i.price,size:i.size||null})),created_at:o.createdAt,updated_at:o.updatedAt}}
app.get('/api/health',(_req,res)=>res.json({ok:true,service:'AccessStore API'}));
app.get('/api/settings',async(_req,res,next)=>{try{const saved=await Settings.findOne({key:'upi_id'}).lean();const cfg=readStoreConfig(saved?.value||process.env.UPI_ID||'');res.json({success:true,settings:{creator_name:'AccessStore',creator_tagline:'Level Up Your Roblox Experience',creator_description:'Welcome to AccessStore — your creator store for gaming gear, merchandise and community picks.',youtube_subscribers:process.env.YOUTUBE_SUBSCRIBERS||'',youtube_videos:process.env.YOUTUBE_VIDEOS||'3',youtube_views:process.env.YOUTUBE_VIEWS||'',youtube_url:process.env.YOUTUBE_URL||'https://www.youtube.com/',instagram_url:process.env.INSTAGRAM_URL||'',discord_url:process.env.DISCORD_URL||'',business_email:process.env.BUSINESS_EMAIL||'',whatsapp_number:process.env.WHATSAPP_NUMBER||'',upi_id:cfg.upi||process.env.UPI_ID||'9958856831@pthdfc',delivery_charge:cfg.delivery,gst_percent:cfg.gst,free_delivery_threshold:cfg.freeThreshold,support_page_url:'/support',hero_heading:'Level Up Your Roblox Experience.',hero_subheading:'Gaming gear, creator merchandise and handpicked products for the community.'}})}catch(e){next(e)}});
app.post('/api/auth/register',authLimiter,async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),name=String(req.body.name||'').trim().slice(0,100),password=String(req.body.password||'');if(!email)return res.status(400).json({error:'Email / username is required'});if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});if(await User.exists({email}))return res.status(409).json({error:'An account with this email / username already exists'});const u=await User.create({name,email,passwordHash:await bcrypt.hash(password,12),role:'customer'});broadcast('user_created',{user:publicUser(u)});res.status(201).json({token:tokenFor(u),user:publicUser(u)})}catch(e){if(e?.code===11000)return res.status(409).json({error:'An account with this email / username already exists'});next(e)}});
app.post('/api/auth/login',authLimiter,async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),u=await User.findOne({email}).select('+passwordHash');if(!u||u.role!=='customer'||!(await bcrypt.compare(password,u.passwordHash)))return res.status(401).json({error:'Invalid customer login details'});res.json({token:tokenFor(u),user:publicUser(u)})}catch(e){next(e)}});
app.post('/api/auth/admin-login',authLimiter,async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),ae=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),ap=String(process.env.ADMIN_PASSWORD||'');if(!ae||!ap)return res.status(503).json({error:'Admin credentials are not configured on the server'});if(email!==ae||password!==ap)return res.status(401).json({error:'Invalid admin login details'});let u=await User.findOne({email}).select('+passwordHash');const hash=await bcrypt.hash(ap,12);if(!u)u=await User.create({name:'Administrator',email,passwordHash:hash,role:'admin'});else if(u.role!=='admin'||!(await bcrypt.compare(ap,u.passwordHash))){u.role='admin';u.passwordHash=hash;u.name=u.name||'Administrator';await u.save()}broadcast('admin_login',{at:new Date().toISOString()});res.json({token:tokenFor(u),user:publicUser(u)})}catch(e){next(e)}});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:publicUser(req.user)}));app.post('/api/auth/logout',(_req,res)=>res.json({success:true}));
app.get('/api/admin/events',(req,res)=>{try{const raw=String(req.query.token||'');if(!raw)return res.status(401).end();const p=jwt.verify(raw,process.env.JWT_SECRET);if(p.role!=='admin')return res.status(403).end();res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache, no-transform');res.setHeader('Connection','keep-alive');res.flushHeaders?.();res.write(`event: connected\ndata: ${JSON.stringify({at:new Date().toISOString()})}\n\n`);addRealtimeClient(res)}catch{return res.status(401).end()}});
app.get('/api/products',async(req,res,next)=>{try{const q={is_active:true};if(req.query.q){const term=String(req.query.q).trim().slice(0,80);q.$or=[{name:new RegExp(term,'i')},{short_description:new RegExp(term,'i')},{description:new RegExp(term,'i')},{tags:new RegExp(term,'i')}]}const ps=await Product.find(q).sort({createdAt:-1}).lean();res.json({success:true,products:ps.map(productOut)})}catch(e){next(e)}});
app.get('/api/products/:slug',async(req,res,next)=>{try{const p=await Product.findOne({slug:req.params.slug,is_active:true});if(!p)return res.status(404).json({error:'Product not found'});res.json({success:true,product:productOut(p)})}catch(e){next(e)}});
app.post('/api/orders',auth,async(req,res,next)=>{try{const{items,shippingAddress,paymentProvider='upi'}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({error:'Cart is empty'});if(items.length>50)return res.status(400).json({error:'Too many items'});if(!shippingAddress?.name||!shippingAddress?.phone||!shippingAddress?.address||!shippingAddress?.city||!shippingAddress?.state||!shippingAddress?.pincode)return res.status(400).json({error:'Complete shipping details are required'});if(!/^\d{10}$/.test(String(shippingAddress.phone).replace(/\s/g,'')))return res.status(400).json({error:'Invalid phone number'});if(!/^\d{6}$/.test(String(shippingAddress.pincode)))return res.status(400).json({error:'Invalid pincode'});const ids=items.map(i=>String(i.productId||i.id||''));if(ids.some(id=>!mongoose.isValidObjectId(id)))return res.status(400).json({error:'Invalid product in cart'});const products=await Product.find({_id:{$in:ids},is_active:true});const byId=new Map(products.map(p=>[String(p._id),p]));const safeItems=[];let subtotal=0;for(const i of items){const id=String(i.productId||i.id||''),p=byId.get(id),qty=Math.floor(Number(i.quantity));if(!p)return res.status(400).json({error:'One or more products are no longer available'});if(!Number.isFinite(qty)||qty<1||qty>50)return res.status(400).json({error:'Invalid quantity'});if(p.stock<qty)return res.status(409).json({error:`${p.name} is out of stock or has insufficient stock`});const price=Number(p.price)||0;subtotal+=price*qty;safeItems.push({product:p._id,name:p.name,image_url:p.image_url||'',price,quantity:qty,size:i.size||undefined})}const order=await Order.create({user:req.user._id,items:safeItems,subtotal,shipping:0,gst:0,total:subtotal,paymentProvider:String(paymentProvider),shippingAddress:{name:String(shippingAddress.name).trim(),phone:String(shippingAddress.phone).trim(),address:String(shippingAddress.address).trim(),apartment:String(shippingAddress.apartment||'').trim(),city:String(shippingAddress.city).trim(),state:String(shippingAddress.state).trim(),pincode:String(shippingAddress.pincode).trim()},email:req.user.email,status:'pending',paymentStatus:'pending'});for(const i of safeItems)await Product.findByIdAndUpdate(i.product,{$inc:{stock:-i.quantity}});const out=orderOut(order);broadcast('new_order',{order:out});res.status(201).json({data:out,rawId:String(order._id),error:null})}catch(e){next(e)}});
app.get('/api/orders',auth,async(req,res,next)=>{try{const os=await Order.find({user:req.user._id}).sort({createdAt:-1});res.json({data:os.map(orderOut),error:null})}catch(e){next(e)}});
app.get('/api/orders/:id',auth,async(req,res,next)=>{try{const q=mongoose.isValidObjectId(req.params.id)?{_id:req.params.id,user:req.user._id}:{orderId:req.params.id,user:req.user._id};const o=await Order.findOne(q);if(!o)return res.status(404).json({error:'Order not found'});res.json({data:orderOut(o),error:null})}catch(e){next(e)}});
app.patch('/api/orders/:id/payment',auth,async(req,res,next)=>{try{const utr=String(req.body.utr||req.body.paymentReference||'').trim().replace(/\s+/g,' ').slice(0,100);if(!utr||utr.length<6)return res.status(400).json({error:'Enter a valid UTR / transaction reference'});const q=mongoose.isValidObjectId(req.params.id)?{_id:req.params.id,user:req.user._id}:{orderId:req.params.id,user:req.user._id};const o=await Order.findOne(q);if(!o)return res.status(404).json({error:'Order not found'});if(o.paymentStatus==='paid')return res.status(409).json({error:'This payment is already verified'});o.paymentReference=utr;o.paymentStatus='pending';await o.save();const out=orderOut(o);broadcast('payment_submitted',{order:out});broadcast('order_updated',{order:out});res.json({success:true,data:out,message:'Payment reference submitted. Your order is pending verification.'})}catch(e){next(e)}});
app.get('/api/track/:orderId',async(req,res,next)=>{try{const o=await Order.findOne({orderId:req.params.orderId});if(!o)return res.status(404).json({error:'Order not found'});const contact=String(req.query.contact||'').trim().toLowerCase();if(contact&&contact!==String(o.email||'').toLowerCase()&&contact!==String(o.shippingAddress?.phone||''))return res.status(404).json({error:'Order not found'});res.json({data:orderOut(o)})}catch(e){next(e)}});
app.get('/api/admin/orders',auth,adminOnly,async(req,res,next)=>{try{const os=await Order.find().sort({createdAt:-1});res.json({data:os.map(orderOut),serverTime:new Date().toISOString()})}catch(e){next(e)}});
app.patch('/api/admin/orders/:id',auth,adminOnly,async(req,res,next)=>{try{const allowed=['pending','confirmed','processing','shipped','delivered','cancelled'],update={};if(req.body.status&&allowed.includes(req.body.status))update.status=req.body.status;if(req.body.paymentStatus&&['pending','paid','failed','refunded'].includes(req.body.paymentStatus))update.paymentStatus=req.body.paymentStatus;if(req.body.paymentReference!==undefined)update.paymentReference=String(req.body.paymentReference).slice(0,200);if(req.body.estimatedDelivery!==undefined)update.estimatedDelivery=String(req.body.estimatedDelivery).slice(0,100);if(req.body.shippingAddress&&typeof req.body.shippingAddress==='object'){const a=req.body.shippingAddress;update.shippingAddress={name:String(a.name||'').trim().slice(0,100),phone:String(a.phone||'').trim().slice(0,30),address:String(a.address||'').trim().slice(0,300),apartment:String(a.apartment||'').trim().slice(0,100),city:String(a.city||'').trim().slice(0,100),state:String(a.state||'').trim().slice(0,100),pincode:String(a.pincode||'').trim().slice(0,10)}}const o=await Order.findByIdAndUpdate(req.params.id,update,{new:true,runValidators:true});if(!o)return res.status(404).json({error:'Order not found'});const out=orderOut(o);broadcast('order_updated',{order:out});res.json({data:out})}catch(e){next(e)}});
app.get('/api/admin/products',auth,adminOnly,async(req,res,next)=>{try{res.json({products:(await Product.find().sort({createdAt:-1})).map(productOut)})}catch(e){next(e)}});
app.post('/api/admin/products',auth,adminOnly,async(req,res,next)=>{try{const body={...req.body,tags:Array.isArray(req.body.tags)?req.body.tags:[],images:Array.isArray(req.body.images)?req.body.images:[]};if(!body.slug&&body.name)body.slug=String(body.name).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const p=await Product.create(body);const out=productOut(p);broadcast('product_updated',{product:out,action:'created'});res.status(201).json({product:out})}catch(e){res.status(400).json({error:e.message})}});
app.patch('/api/admin/products/:id',auth,adminOnly,async(req,res,next)=>{try{const body={...req.body};if(body.tags!==undefined)body.tags=Array.isArray(body.tags)?body.tags:[];if(body.images!==undefined)body.images=Array.isArray(body.images)?body.images:[];const p=await Product.findByIdAndUpdate(req.params.id,body,{new:true,runValidators:true});if(!p)return res.status(404).json({error:'Product not found'});const out=productOut(p);broadcast('product_updated',{product:out,action:'updated'});res.json({product:out})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/admin/products/:id',auth,adminOnly,async(req,res,next)=>{try{const p=await Product.findByIdAndDelete(req.params.id);if(!p)return res.status(404).json({error:'Product not found'});broadcast('product_updated',{productId:req.params.id,action:'deleted'});res.json({success:true})}catch(e){next(e)}});
app.get('/api/admin/users',auth,adminOnly,async(req,res,next)=>{try{const users=await User.find().select('name email role createdAt').sort({createdAt:-1}).lean();const orders=await Order.find().sort({createdAt:-1}).lean();const latest=new Map();for(const o of orders){const key=String(o.user);if(!latest.has(key))latest.set(key,orderOut(o))}res.json({users:users.map(u=>({...u,id:String(u._id),created_at:u.createdAt,latest_order:latest.get(String(u._id))||null}))})}catch(e){next(e)}});
app.patch('/api/admin/users/:id',auth,adminOnly,async(req,res,next)=>{try{const update={};if(req.body.name!==undefined)update.name=String(req.body.name).trim().slice(0,100);if(req.body.email!==undefined)update.email=String(req.body.email).trim().toLowerCase();if(req.body.role==='customer'||req.body.role==='admin')update.role=req.body.role;const u=await User.findByIdAndUpdate(req.params.id,update,{new:true,runValidators:true}).select('name email role createdAt');if(!u)return res.status(404).json({error:'User not found'});const out={...publicUser(u),created_at:u.createdAt};broadcast('user_updated',{user:out});res.json({user:out})}catch(e){if(e?.code===11000)return res.status(409).json({error:'That email / ID is already in use'});res.status(400).json({error:e.message})}});
app.get('/api/admin/settings',auth,adminOnly,async(_req,res,next)=>{try{const saved=await Settings.findOne({key:'upi_id'}).lean();const cfg=readStoreConfig(saved?.value||process.env.UPI_ID||'');res.json({settings:{upi_id:saved?.value||'',upi:cfg.upi,delivery:cfg.delivery,gst:cfg.gst,freeThreshold:cfg.freeThreshold}})}catch(e){next(e)}});
app.patch('/api/admin/settings',auth,adminOnly,async(req,res,next)=>{try{const current=readStoreConfig((await Settings.findOne({key:'upi_id'}).lean())?.value||process.env.UPI_ID||'');const cfg={upi:String(req.body.upi??req.body.upi_id??current.upi).trim().slice(0,120),delivery:Math.max(0,Number(req.body.delivery??current.delivery)||0),gst:Math.max(0,Number(req.body.gst??current.gst)||0),freeThreshold:Math.max(0,Number(req.body.freeThreshold??current.freeThreshold)||999)};const value=JSON.stringify(cfg);await Settings.findOneAndUpdate({key:'upi_id'},{key:'upi_id',value},{upsert:true,new:true,setDefaultsOnInsert:true});broadcast('settings_updated',{settings:cfg});res.json({success:true,settings:{upi_id:value,upi:cfg.upi,delivery:cfg.delivery,gst:cfg.gst,freeThreshold:cfg.freeThreshold}})}catch(e){next(e)}});
app.use((err,_req,res,_next)=>{console.error(err);if(err?.message==='CORS origin not allowed')return res.status(403).json({error:'CORS origin not allowed'});res.status(500).json({error:'Internal server error'})});
const port=Number(process.env.PORT||5000);if(!process.env.MONGO_URI||!process.env.JWT_SECRET){console.error('MONGO_URI and JWT_SECRET are required');process.exit(1)}mongoose.connect(process.env.MONGO_URI).then(()=>app.listen(port,'0.0.0.0',()=>console.log(`AccessStore API listening on ${port}`))).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});
