import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import rateLimit from 'express-rate-limit';
import authRoutes from './routes/auth.js';
import productRoutes from './routes/products.js';
import { requireAuth, requireAdmin } from './middleware/auth.js';
import Order from './models/Order.js';
import Product from './models/Product.js';

const app=express(); const PORT=process.env.PORT||5000;
app.set('trust proxy',1); app.use(cors({origin:process.env.FRONTEND_URL?process.env.FRONTEND_URL.split(',').map(v=>v.trim()):true,credentials:true})); app.use(express.json({limit:'1mb'}));
app.use('/api',rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
app.get('/health',(_req,res)=>res.json({success:true,service:'AccessStore API',database:mongoose.connection.readyState===1?'connected':'disconnected'}));
app.get('/api/health',(_req,res)=>res.json({success:true,service:'AccessStore API'}));
app.use('/api/auth',authRoutes); app.use('/api/products',productRoutes);
app.get('/api/me',requireAuth,(req,res)=>res.json({success:true,user:req.user}));
app.post('/api/orders',requireAuth,async(req,res,next)=>{try{const {items,shippingAddress}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({success:false,message:'Cart is empty'});const ids=items.map(i=>i.productId);const products=await Product.find({_id:{$in:ids},is_active:true});const map=new Map(products.map(p=>[p._id.toString(),p]));const orderItems=[];let subtotal=0;for(const i of items){const p=map.get(String(i.productId));const q=Math.max(1,Math.min(99,Number(i.quantity)||1));if(!p||p.stock<q)return res.status(400).json({success:false,message:`Product unavailable: ${i.productId}`});orderItems.push({product:p._id,name:p.name,image_url:p.image_url,price:p.price,quantity:q,size:i.size});subtotal+=p.price*q;}const order=await Order.create({user:req.user.sub,items:orderItems,subtotal,shipping:0,total:subtotal,shippingAddress});res.status(201).json({success:true,order});}catch(e){next(e)}});
app.get('/api/orders',requireAuth,async(req,res,next)=>{try{res.json({success:true,orders:await Order.find({user:req.user.sub}).sort({createdAt:-1}).lean()})}catch(e){next(e)}});
app.get('/api/admin/orders',requireAuth,requireAdmin,async(req,res,next)=>{try{res.json({success:true,orders:await Order.find().sort({createdAt:-1}).populate('user','email name').lean()})}catch(e){next(e)}});
app.patch('/api/admin/orders/:id/status',requireAuth,requireAdmin,async(req,res,next)=>{try{const allowed=['pending','confirmed','processing','shipped','delivered','cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({success:false,message:'Invalid status'});const order=await Order.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});if(!order)return res.status(404).json({success:false,message:'Order not found'});res.json({success:true,order})}catch(e){next(e)}});
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({success:false,message:'Internal server error'})});
async function start(){if(!process.env.MONGO_URI)throw Error('MONGO_URI is required');if(!process.env.JWT_SECRET)throw Error('JWT_SECRET is required');await mongoose.connect(process.env.MONGO_URI,{serverSelectionTimeoutMS:10000});console.log('MongoDB connected');app.listen(PORT,'0.0.0.0',()=>console.log(`AccessStore API listening on ${PORT}`))} start().catch(e=>{console.error('Startup failed:',e.message);process.exit(1)});
